### PR TITLE
FIX #662 and make universal archive options customizable

### LINKED ISSUE #662: tar is expected to have --force-local option
I am wanting to use `sbt-native-packager` on FreeBSD (10.2).  The base-installation of `tar` in this version of FreeBSD [lacks the `--force-local` option](https://www.freebsd.org/cgi/man.cgi?query=tar&apropos=0&sektion=0&manpath=FreeBSD+10.2-RELEASE&arch=default&format=html).  I have gnu's _tar_, which has the `--force-local` option, installed on the machine, but it is named `gtar` rather than `tar`.

[It seems](https://github.com/sbt/sbt-native-packager/blob/master/src/main/scala/com/typesafe/sbt/packager/universal/Archives.scala#L182) that both the name of the _tar_ executable and the `--force-local` option are hard-coded in the `sbt-native-packager` source code.  On my FreeBSD machine, invoking the `universal:packageZipTarball` task fails with a complaint about the `--force-local` option.

Is there any simple work-around of this issue that does not involve renaming the commands on my operating system?  If not, is the ability to tell `sbt-native-packager` to refrain from including the `--force-local` option when invoking tar, or changing the name of the _tar_ executable a feature that might eventually find its way into this project?

### PR DESCRIPTION
**Pull request by muuki88**
cc @mackler

### CODE REVIEW

File: src/main/scala/com/typesafe/sbt/packager/universal/Archives.scala [hunk 1]
```diff
@@ -58,9 +60,10 @@ object Archives {
    *  @param name of output (without extension)
    *  @param mappings included in the output
    *  @param top level directory : NOT USED
+   *  @param options  NOT USED
    *  @return dmg file
    */
-  def makeDmg(target: File, name: String, mappings: Seq[(File, String)], top: Option[String]): File = {
+  def makeDmg(target: File, name: String, mappings: Seq[(File, String)], top: Option[String], options: Seq[String]): File = {
```
Comment (muuki88) [inline src/main/scala/com/typesafe/sbt/packager/universal/Archives.scala]: Codacy Issue found: [Method is longer than 50 lines](https://www.codacy.com/app/nepomukseiler/sbt-native-packager/file/946190549/issues/source?bid=2040925&fileBranchId=2849134#l66)

**Comment by mackler** [comment]
Thanks for doing this.  I can see I would have been unable to figure this out myself.

**Comment by muuki88** [comment]
@sumkincpp we made the `--force-local` customizable. With the next release you will can add this option for your build.
