### PR TITLE
Fix launcher jar paths not being quoted on Windows

### LINKED ISSUE #913: universal:packageBin not working with spaces in path (windows / play application)
Hi

My Problem:
When I use `activator dist` to produce a zip file of my play application, unzip this application in a path with spaces 
let's say `D:\unfinished-path with spaces\myproj-1.0`
and run the .bat file I get the following Error:

`Error: Unable to access jarfile D:\unfinished-path`

build.sbt:
```
name := """MyProj"""

version := "1.0"

lazy val root = (project in file(".")).enablePlugins(
  PlayJava,
  JavaAppPackaging,
  UniversalPlugin,
  SonarRunnerPlugin,
  LauncherJarPlugin
)

scalaVersion := "2.11.7"

...

mappings in Universal ++= directory(baseDirectory.value / "public")
mappings in Universal += Tuple2(file("conf/production.conf"), "conf/production.conf")
mappings in Universal += Tuple2(file("conf/logback.xml"), "conf/logback.xml")
....
```

and plugins.sbt

```
// The Play plugin
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.5.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.3.3")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.1.4")
```

Adding `"` to the generated .bat file in `D:\unfinished-path with spaces\myproj-1.0\bin\myproj.bat`

on line 132 before %APP_LIB_DIR%... changing it from
`set "APP_MAIN_CLASS=-jar %APP_LIB_DIR%\myproj.myproj-1.0-launcher.jar"`
to
`set "APP_MAIN_CLASS=-jar "%APP_LIB_DIR%\myproj.myproj-1.0-launcher.jar"`

lets the application start without the error

### PR DESCRIPTION
**Pull request by dwickern**
If you run the batch script from `C:\Program Files\my-app\bin\my-app.bat` you'll get an error like this:
> Error: Unable to access jarfile C:\Program

#581 fixed the path being quoted in the bash script, but it still wasn't quoted in the bat script.

Before:
```bat
set "APP_MAIN_CLASS=-jar %APP_LIB_DIR%\app-1.0-SNAPSHOT-launcher.jar"
```
After:
```bat
set "APP_MAIN_CLASS=-jar "%APP_LIB_DIR%\app-1.0-SNAPSHOT-launcher.jar""
```

Fixes #913

### CODE REVIEW

**Comment by muuki88** [comment]
Thanks a lot for your work 😍
I'm currently on vacation and will review this after the 20.10

File: src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BashStartScriptPlugin.scala [hunk 1]
```diff
@@ -208,15 +208,6 @@ object BashStartScriptPlugin extends AutoPlugin {
       script
     }
 
-    private[this] def mainClassReplacement(mainClass: String): String = {
```
Comment (muuki88) [inline src/main/scala/com/typesafe/sbt/packager/archetypes/scripts/BashStartScriptPlugin.scala]: Thanks for cleaning this up. The quoting is now done at a much better place :)
